//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_TutelaProvisoria.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensagensSistema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensSistema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCC_TutelaProvisoria.Recursos.MensagensSistema", typeof(MensagensSistema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busca de Jurisprudências finalizada com sucesso!.
        /// </summary>
        internal static string BuscaJurisprudenciaFinalizada {
            get {
                return ResourceManager.GetString("BuscaJurisprudenciaFinalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro carregue um arquivo word para poder lê-lo..
        /// </summary>
        internal static string CarregueAlgumArquivo {
            get {
                return ResourceManager.GetString("CarregueAlgumArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado: .
        /// </summary>
        internal static string ErroPadrao {
            get {
                return ResourceManager.GetString("ErroPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leu todas as tutelas!
        ///Quantidade de tutelas lidas: .
        /// </summary>
        internal static string LeuTodasTutelas {
            get {
                return ResourceManager.GetString("LeuTodasTutelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nada havia nesta pasta. Escolha uma pasta que contenha arquivos word :/.
        /// </summary>
        internal static string PastaVazia {
            get {
                return ResourceManager.GetString("PastaVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A porcentagem de semelhança entre as tutelas analisadas é de aproximadamente .
        /// </summary>
        internal static string PorcentagemSimilaridade {
            get {
                return ResourceManager.GetString("PorcentagemSimilaridade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant. de palavras encontradas: .
        /// </summary>
        internal static string QuantidadePalavrasEncontradas {
            get {
                return ResourceManager.GetString("QuantidadePalavrasEncontradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantida de tutelas lidas: .
        /// </summary>
        internal static string QuantidadeTutelasLidas {
            get {
                return ResourceManager.GetString("QuantidadeTutelasLidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione dois arquivos para comparação..
        /// </summary>
        internal static string SelecionarDois {
            get {
                return ResourceManager.GetString("SelecionarDois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutelas excluídas com sucesso!
        ///{0} tutelas foram excluídas..
        /// </summary>
        internal static string TutelasExcluidasSuccess {
            get {
                return ResourceManager.GetString("TutelasExcluidasSuccess", resourceCulture);
            }
        }
    }
}
